// GTM exports
export {
  pushToDataLayer,
  setFunnelContext,
  getFunnelContext,
  setFlowType,
  getFlowType,
  trackQuoteFunnel,
  trackFunnelStart as trackGTMFunnelStart,
  trackQuestionView,
  trackQuestionAnswered,
  trackQuestionNavigation,
  trackQuestionnaireComplete as trackGTMQuestionnaireComplete,
  trackProfileView,
  trackProfileComplete,
  trackProductCardClick,
  trackProductSelectionChange,
  trackComparisonModalOpen,
  trackLeadSubmitted as trackGTMLeadSubmitted,
  trackLeadSubmissionError,
  trackSelectionPageView,
  trackContactFormView,
  trackModifyCriteriaModalView,
  trackCriteriaModified,
  trackCustomNeedPageView,
  trackCustomNeedContactView,
  trackComparisonModalView,
  trackProductModalView,
  trackFunnelAbandonment,
  trackFormValidationError,
  trackFormValidationErrors,
  trackDeviceInfo,
  trackTrafficSource,
  resetTrackingState,
} from './gtm';

// GA4 exports
export {
  trackEvent,
  trackPageView,
  trackFunnelStart as trackGA4FunnelStart,
  trackQuestionnaireComplete as trackGA4QuestionnaireCompleteSimple,
  trackLeadSubmitted as trackGA4LeadSubmittedSimple,
  trackError,
  trackGA4QuestionAnswered,
  trackGA4QuestionnaireComplete,
  trackGA4ProfileComplete,
  trackGA4SupplierSelection,
  trackGA4LeadSubmitted,
} from './ga4';

// Hotjar exports
export {
  hotjarEvent,
  hotjarIdentify,
  hotjarStateChange,
  hotjarTagRecording,
  hotjarTriggerSurvey,
  HOTJAR_TAGS,
  tagHotjarUser,
} from './hotjar';
